### ISSUE TITLE
Cross platform build support

### ISSUE THREAD

**Issue by ljoonal** [Banane9/MonkeyLoader#11]
Currently `pdb2mdb.exe` is bundled with the repo, which is fully windows only. This makes building this mod loader impossible or at the very least very very impractical on other operating systems.
I'd expect that `dotnet build` should be made to just work out of the box to lower the bar for new contributors :wink:

**Comment by Banane9** [comment]
I'm not sure how the build on Linux handles it, but the mdbs are necessary for debugging support with mono, so ideally any solution should keep outputting those as well.

**Comment by ljoonal** [comment]
I think that MDB generation might only be properly supported on windows, even though pdb2mdb exists on linux mono too, due to https://github.com/dotnet/msbuild/issues/4223

**Comment by Banane9** [comment]
Ah, just makes you love mono 🥲

Debugging on windows builds it is, then.
