### ISSUE TITLE
Load mods from .zip / .nupkg files

### ISSUE THREAD

**Issue by Banane9** [Banane9/MonkeyLoader#5]
Mods should be loadable from zip files as virtual file systems. This allows shipping one file with any dependencies, assets and metadata separate from the actual assembly dll.

nuget.exe could be used to resolve dependencies on nuget packages or even mods published through nuget.

**Comment by Nihlus** [comment]
Calling out to nuget.exe is not required (nor recommended, since it's not very portable) - better to interface directly using the available libraries! https://www.nuget.org/packages/NuGet.Protocol/ et. al
